name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Test
        run: ./test.sh
